AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudformation Template for ECR Repository
Parameters:
  RegistryName:
    Type: String
    Description: ECR name
Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName:
        Ref: RegistryName
Outputs:
  ECR:
    Description: 'ECR '
    Value:
      Ref: ECR